//LOGINSIGNUP CONSTANTS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const EMAIL_CHANGE_TEXT = 'USERNAME_EMAIL_CHANGE_TEXT';
export const PASSWORD_CHANGE_TEXT = 'PASSWORD_CHANGE_TEXT';
export const CONFIRM_PASSWORD_CHANGE_TEXT = 'CONFIRM_PASSWORD_CHANGE_TEXT';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const IS_FETCHING_TRUE = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';

//MAIN CONSTANTS
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const SET_FETCHING = 'SET_FETCHING';
